const routes = {
  home: '/',
  zingChart: '/zing-chart',
  radio: '/radio',
  newMusic: '/moi-phat-hanh',
  topic: '/hub',
  library: '/my-music',
  top100: '/top100',
  history: '/my-music/history',
  favorite: '/my-music/song/favorite',
  playlist: '/my-music/library/playlist',
  upload: '/my-music/song/upload',
  album: '/my-music/album',
  detailAlbum: '/album/:id',
  detailSong: '/song/:id',
  notFound: '*',
  login: '/login',
  register: '/register',
};
export default routes;
